---
debug: false
trace: false
logging:
  level:
    org:
      hibernate:
        SQL: info
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/ona"
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      generate_statistics: true
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  liquibase:
    change-log: "classpath:db/db-changelog.xml"