debug: false
trace: false

spring:
  main:
    web-application-type: NONE
  profiles:
    active: prod
  liquibase:
    enabled: false
    change-log: "classpath:db/changelog.xml"
    rollback-file: "I://development//rollback.sql"