debug: false
trace: false
logging:
  level:
    org:
      hibernate:
        SQL: ${SQL_MODE:error}
spring:
  main:
    web-application-type: NONE
  profiles:
    active: ${APP_MODE:dev}
  liquibase:
    enabled: false
    change-log: "classpath:db/changelog.xml"
    rollback-file: "rollback.sql"

  jpa:
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 5
        order_inserts: true

ona:
  json-path: ${JSON_PATH:D:\\dev\\python\\ona-download\\downloads\\json\\}
  output-path: ${OUTPUT_PATH:D:\\dev\\python\\ona-download\\downloads\\converted\\}
  compare-path: ${COMPARE_PATH:D:\\dev\\python\\ona-download\\downloads\\onaData\\}