debug: false
trace: false

spring:
  main:
    web-application-type: NONE
  profiles:
    active: cmd
  liquibase:
    enabled: false
    change-log: "classpath:db/changelog.xml"
    rollback-file: "I://development//rollback.sql"

ona:
  folder-path: "I://development//python//ona-download//downloads//json//"