debug: false
trace: false
spring:
  main:
    web-application-type: none
  profiles:
    active: ${APP_MODE:dev}

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration

ona:
  json-path: ${JSON_PATH:D:\\dev\\python\\ona-download\\downloads\\json\\}
  output-path: ${OUTPUT_PATH:D:\\dev\\python\\ona-download\\downloads\\converted\\}
  compare-path: ${COMPARE_PATH:D:\\dev\\python\\ona-download\\downloads\\onaData\\}

ftp:
  host: ${FTP_HOST:127.0.0.1}
  port: ${FTP_PORT:21}
  username: ${FTP_USER:127.0.0.1}
  password: ${FTP_PASS:127.0.0.1}
  privateKey: ${FTP_KEY_FILE:127.0.0.1}
  privateKeyPhrase: ${FTP_KEY_PHRASE:127.0.0.1}
  remoteDir: ${FTP_DIR:}